### ISSUE TITLE
Support TLS 1.1 and 1.2 in .NET 4.5

### ISSUE THREAD

**Issue by jbrestan** [kerryjiang/SuperWebSocket#14]
Hi Kerry,

I found out that a SuperWebSocket server only supports TLS 1.0 even on .NET 4.5 when I use security="tls" configuration.

I've checked with Wireshark that even on Windows Server 2012 R2 with .NET 4.5.2 the SuperWebSocket only supports up to TLS 1.0.

When I use WebSocket4Net as a client, the version is capped to 1.0 by the client. When I connected from browser JS, client hello contained version 1.2 but server responded with 1.0.
Custom test client/server app between two test servers (same configuration - WS 2012 R2, .NET 4.5.2) managed to use TLS 1.2, so it should be supported by the system and platform in question.

The tested SuperWebSocket version was a NuGet package 0.9.0.2

Thank you,
Honza

**Comment by kerryjiang** [comment]
Yes, I improved the SuperSocket to support TLS/SSL better, but have not migrated to SuperWebSocket yet.

**Comment by jbrestan** [comment]
Closing this old issue since this is now solved in newer versions and the improved NuGet package structure and releases.
