### ISSUE TITLE
Support for websocket compression extensions?

### ISSUE THREAD

**Issue by Costigan** [kerryjiang/SuperWebSocket#15]
Hi Kerry,
  Have you considered supporting the per-message deflate extension for websockets?
 Thanks,
   Mark Shirley

**Comment by kerryjiang** [comment]
yes, could you share some reference with me?

**Comment by Costigan** [comment]
Kerry,
  Here are some references.
First, here is the request for comment ... the specification itself:

https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-21

The compression algorithm used is DEFLATE
https://tools.ietf.org/html/rfc1951

.NET 4.5 includes this implementation of DEFLATE in
System.IO.Compression.DeflateStream.

https://msdn.microsoft.com/en-us/library/system.io.compression.deflatestream(v=vs.110).aspx

This class can both compress and decompress byte streams.

I haven't been able to find a list of browsers that implement this
extension.  I've found discussion of adding it to Chrome (from
several years ago):
https://code.google.com/p/chromium/issues/detail?id=229290

Here's someone who has implemented websockets in c# and was having
trouble with the DeflateStream class:
http://stackoverflow.com/questions/26051786/websocket-permessage-deflate-c-sharp

The last reply to this question points at some source for another c#
implementation that the writer says works.  (I haven't tried it yet.)
 - Mark

**Comment by kerryjiang** [comment]
Thanks, I'll look into these!

**Comment by Costigan** [comment]
Kerry,
  Have you had a chance to look at compression yet?
 Thanks,
     Mark
