### ISSUE TITLE
现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作

### ISSUE THREAD

**Issue by shllove** [kerryjiang/SuperWebSocket#26]
2015-11-07 15:20:56,556 [40280] ERROR PWSS:port_a.b.c.d - Session: d41f2306-e4fe-4cfc-a639-3651f9def6be/e.f.g.h:48747
Unexpected error
System.InvalidOperationException: "现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。";
   在 System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   在 System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   在 SuperSocket.SocketEngine.AsyncSocketSession.StartReceive(SocketAsyncEventArgs e, Int32 offsetDelta) 位置 \SuperSocket-master\SocketEngine\AsyncSocketSession.cs:行号 148

**Comment by kerryjiang** [comment]
Could you tell me the version number?

**Comment by shllove** [comment]
直接下载的master主线代码，偶尔出现，非必现

**Comment by kerryjiang** [comment]
OK, 我刚刚了引用里的SuperSocket, 你能拉一下最新代码然后试一下吗？
