### ISSUE TITLE
dll可以用NuGget来管理

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperWebSocket#28]
https://github.com/andburn/hdt-plugin-statsconverter/pull/6
 it is generally not a good idea to add external libraries into version control software such as git.
The preferred way to add external packages to .NET is to use NuGet and its package restore function which is integrated into Visual Studio.

可以了解下这个https://docs.nuget.org/Consume/Package-Restore

**Comment by kerryjiang** [comment]
Yes, I have started to use nuget in SuperSocket. But because SuperWebSocket will be merged into SuperSocket fully, so I don't do anything for SuperWebSocket for now.

**Comment by chucklu** [comment]
ok
