### ISSUE TITLE
websocket client closing while connect with secured mode

### ISSUE THREAD

**Issue by PhanHoangAnh** [kerryjiang/SuperWebSocket#4]
I try some tests with SuperWebSocket (1.5.3.0)
Actually, the secure websocket client in Browser can't connect to server..???
My code in C#:
[code]
namespace SuperWebSocket.Samples.BasicConsole
{
    class Program
    {
        static void Main(string[] args)
        {
						//Console.WriteLine("Press any key to start the WebSocketServer!");

						//Console.ReadKey();
						//Console.WriteLine();

            var appServer = new WebSocketServer();
						var config = new RootConfig();
						var serverConfig = new ServerConfig
								{
										Name = "SecureSuperWebSocket",
										Ip = "Any",
										Port = 8089,
										Mode = SocketMode.Tcp,
										Security = "tls",
										Certificate = new SuperSocket.SocketBase.Config.CertificateConfig
										{
												FilePath = @"E:\AMIS\Labs\AlchemySSL\mtax.misa.local.pfx",
												Password = "12345678",
												//IsEnabled = true
										}
								};

						

            //Setup the appServer
						//if (!appServer.Setup(2012)) //Setup with listening port
						if (!appServer.Setup(config,serverConfig ))
            {
                Console.WriteLine("Failed to setup!");
                Console.ReadKey();
                return;
            }

            appServer.NewMessageReceived += new SessionHandler<WebSocketSession, string>(appServer_NewMessageReceived);
						appServer.NewSessionConnected += new SessionHandler<WebSocketSession>(appServer_NewSessionConnected);
						appServer.SessionClosed += new SessionHandler<WebSocketSession, CloseReason>(appServer_SessionClosed);
						

            Console.WriteLine();

            //Try to start the appServer
            if (!appServer.Start())
            {
                Console.WriteLine("Failed to start!");
                Console.ReadKey();
                return;
            }

            Console.WriteLine("The server started successfully, press key 'q' to stop it!");

            while (Console.ReadKey().KeyChar != 'q')
            {
                Console.WriteLine();
                continue;
            }						

            //Stop the appServer
            appServer.Stop();

            Console.WriteLine();
            Console.WriteLine("The server was stopped!");
            Console.ReadKey();
        }

				static void appServer_SessionClosed(WebSocketSession session, CloseReason value)
				{
						Console.WriteLine(value);
				}

				static void appServer_NewSessionConnected(WebSocketSession session)
				{
						foreach(var item in session.Items){
								Console.WriteLine(item);
						}
						//appServer.BasicSecurity
						
								Console.WriteLine(session.AppServer.BasicSecurity);
								Console.WriteLine(session.AppServer.Certificate.ToString());

						
				}

        static void appServer_NewMessageReceived(WebSocketSession session, string message)
        {
            //Send the received message back
            session.Send("Server: " + message);
        }
    }
}
[/code]
and my Javascript in page here
[code]
        <script type="text/javascript">
            var noSupportMessage = "Your browser cannot support WebSocket!";
            var ws;

            function appendMessage(message) {
                $('body').append(message);
            }

            function connectSocketServer() {
                var support = "MozWebSocket" in window ? 'MozWebSocket' : ("WebSocket" in window ? 'WebSocket' : null);

                if (support == null) {
                    appendMessage("* " + noSupportMessage + "<br/>");
                    return;
                }

                appendMessage("* Connecting to server ..<br/>");
                // create a new websocket and connect
                ws = new window[support]('wss://localhost:8089/cho,moe,ga');

                // when data is comming from the server, this metod is called
                ws.onmessage = function (evt) {
                    appendMessage("# " + evt.data + "<br />");
                };

                // when the connection is established, this method is called
                ws.onopen = function () {
                    appendMessage('* Connection open<br/>');
                    $('#messageInput').attr("disabled", "");
                    $('#sendButton').attr("disabled", "");
                    $('#connectButton').attr("disabled", "disabled");
                    $('#disconnectButton').attr("disabled", "");
                };

                // when the connection is closed, this method is called
                ws.onclose = function () {
                		appendMessage('* Connection closed<br/>');
                		$('#messageInput').attr("disabled", "disabled");
                		$('#sendButton').attr("disabled", "disabled");
                		$('#connectButton').attr("disabled", "");
                		$('#disconnectButton').attr("disabled", "disabled");                		
                }
            }

            function sendMessage() {
                if (ws) {
                    var messageBox = document.getElementById('messageInput');
                    ws.send(messageBox.value);
                    messageBox.value = "";
                }
            }

            function disconnectWebSocket() {
                if (ws) {
                    ws.close();
                }
            }

            function connectWebSocket() {
                connectSocketServer();
            }

            window.onload = function () {
                $('#messageInput').attr("disabled", "disabled");
                $('#sendButton').attr("disabled", "disabled");
                $('#disconnectButton').attr("disabled", "disabled");
            }
   ... 
[/code]
Could you please help me to solve this problem..??

**Comment by nive20** [comment]
Hi Kerry I am getting error on web console.
Network Error 12029, A connection with the server could not be established
in this line:
var serviceUrl = 'wss://127.0.0.1:2013/';
var   ws = new WebSocket(serviceUrl);
